version: '3.8'
services:
  database:
    container_name: pucminas_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: universidade
    ports:
      - "5433:5432"
    volumes:
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
